name: Deploy to Main

on:
  push:
    branches:
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        continue-on-error: true
        run: npm run build

      - name: List build directory
        run: ls -la build

      - name: Extract commit info
        id: extract-info
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(date -u +%Y%m%d)" >> $GITHUB_ENV

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes to Dev
        run: |
          git add .
          git commit -m "Committing changes before checkout to test"

      - name: Checkout test branch
        run: |
          git fetch origin
          git checkout test

      # - name: Remove all files except .gitignore in test
      #   run: |
      #     find . -not -name '.gitignore'

      - name: Copy build files
        run: |
          cp -r build/* .

      - name: Commit and push build to test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          COMMIT="${{ env.COMMIT_HASH }}.${{ env.COMMIT_DATE }}"
          git commit -m "Deploy build $COMMIT to test"
          git push origin test 